updated choose command
Xirado/Bean pull request #12
Opened 2022-01-11 21:22 UTC by Progame03

I've updated the choose command to take up to ten possible choices (similar to Dank Memer)

2022-01-11 21:35 UTC, Xirado commented on src/main/java/at/xirado/bean/command/slashcommands/ChooseCommand.java
> +import javax.swing.text.html.Option;
Please remove

2022-01-11 21:35 UTC, Xirado commented on src/main/java/at/xirado/bean/command/slashcommands/ChooseCommand.java
>          setCommandData(new CommandData("choose", "Chooses between 2 things.")
The description should be updated

2022-01-11 21:35 UTC, Xirado commented on src/main/java/at/xirado/bean/command/slashcommands/ChooseCommand.java
> +        if(checkOptions(chooseOptions)){
This isn't necessary. The `SlashCommandContext` methods are configured to not allow those mentions

2022-01-12 05:45 UTC, Progame03 commented
On it, doing the changed asap

2022-01-12 10:03 UTC, Progame03 commented
done

2022-01-12 10:05 UTC, Xirado requested changes

2022-01-12 10:05 UTC, Xirado commented on src/main/java/at/xirado/bean/command/slashcommands/ChooseCommand.java
> +                .addOption(OptionType.STRING, "3rd", "Third argument.", false)
```suggestion
                .addOption(OptionType.STRING, "3rd", "Third argument.")
```

This is idempotent

2022-01-12 10:12 UTC, Progame03 commented
changes done

2022-01-12 10:19 UTC, Xirado approved these changes

2022-01-12 10:20 UTC, merged